spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "${DB_URL}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
  data:
    redis:
      host: "${REDIS_HOST}"
      port: "${REDIS_PORT}"
jwt:
  secret: "${JWT_SECRET}"
external:
  kafka:
    endpoint: "${KAFKA_ENDPOINT}"
