spring:
  application:
    name: AuthService
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  cloud:
    aws:
      region:
        static: us-east-1
  flyway:
    enabled: true
    baseline-on-migrate: true
  profiles:
    active: local
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true